name: Run Selenium Script

on:
  workflow_dispatch: # Run Manually

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Chromium (Snap)
        run: |
          sudo snap install chromium

      - name: Install ChromeDriver matching Chromium
        run: |
          CHROMIUM_VERSION=$(chromium --version | awk '{print $2}')
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROMIUM_VERSION")
          wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$DRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run master.py
        env:
          PYTHONUNBUFFERED: 1
        run: python master.py

